emulator: main.cpp cpu/1001_x8.cpp loader/loader.cpp aux_mem/aux_mem.cpp os/os.cpp aux_mem_loader/aux_mem_loader.cpp ISRs/output_isr.cpp
	g++ -o emulator main.cpp cpu/1001_x8.cpp loader/loader.cpp aux_mem/aux_mem.cpp os/os.cpp aux_mem_loader/aux_mem_loader.cpp ISRs/output_isr.cpp -I.
	